name: Laravel CI/CD

on:
  push:
    branches:
      - main  # This deploys when there is a push to the main branch. Change if necessary.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.11'  # Set your PHP version here
        extensions: mbstring, intl, mysqli
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate application key
      run: php artisan key:generate --force

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install NPM dependencies
      run: npm install

    - name: Build assets
      run: npm run production

    - name: Upload files to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        rsync -avz --exclude='node_modules' --exclude='.git' ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/your-app-directory

    - name: Run migrations
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /var/www/html/your-app-directory && php artisan migrate --force"
